apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-platform
data:
  EUREKA_URL: "http://eureka-service:8761/eureka"
  DB_USER: "postgres"
  SPRING_PROFILES_ACTIVE: "prod"
